### ISSUE TITLE
[Feature request] Please add game_by_id method

### ISSUE THREAD

**Issue by swasher** [steveYeah/PyBomb#17]
Please add game_by_id method, which return response object with one game, related with game's id number, such as:

```
id = 6795

response = games_client.game_by_id(
   id = id
)

print(response.results.name)
# Baldur's Gate II: Throne of Bhaal
```

**Comment by steveYeah** [comment]
Hey! That will be in the `Game` client I think. I started that a while back (https://github.com/steveYeah/PyBomb/pull/18) so will see if that is good to go in soon. 👍

**Comment by steveYeah** [comment]
Game client is available but not documented as yet. More updates coming soon
