### ISSUE TITLE
Add PlatformClient

### ISSUE THREAD

**Issue by steveYeah** [steveYeah/PyBomb#30]
Add client to handle the fetching of platforms as seen in the [GiantBomb docs](https://www.giantbomb.com/api/documentation/#toc-0-29)

This will look similar to the existing [GameClient](https://github.com/steveYeah/PyBomb/blob/master/src/pybomb/clients/game_client.py), and have just one method, `fetch`

Tests required too, so take a look at the tests for the GameClient for some help there 👍

**Comment by igotinfected** [comment]
Hey! Didn't know GiantBomb had a public API, willing to take a look at this tonight ;)

**Comment by steveYeah** [comment]
@igotinfected go for it! Have fun, and give me a shout if you need any help :)

**Comment by igotinfected** [comment]
@steveYeah will do! thanks 😊
